name: commandee_mobile
description: "A new Flutter project."
publish_to: 'none'

# Versão do aplicativo
version: 1.0.0+1

# Ambiente
environment:
  sdk: ">=3.0.0 <4.0.0"

# Dependências principais
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

# Dependências para desenvolvimento e testes
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Configurações específicas do Flutter
flutter:
  uses-material-design: true

  assets:
    - lib/assets/icons/Foods/combo_icon.png
    - lib/assets/icons/Foods/dessert_icon.png
    - lib/assets/icons/Foods/drink_icon.png
    - lib/assets/icons/Foods/salty_icon.png
    - lib/assets/icons/Logo/logo.png

